name: CI
on:
  push:
    branches:
      - main
      - "v*"
    tags:
      - "v*"
  pull_request:

jobs:
  lint:
    name: Go Lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.x

      - name: Install Staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@v0.4.3

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Lint Go Code
        run: staticcheck ./...

  test:
    name: Go Test
    runs-on: ubuntu-latest
    env:
      GOPATH: ${{ github.workspace }}/go
      GOBIN: ${{ github.workspace }}/go/bin
    defaults:
      run:
        working-directory: ${{ env.GOPATH }}/src/github.com/bbengfort/noaalert
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.x

      - name: Cache Speedup
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          path: ${{ env.GOPATH }}/src/github.com/bbengfort/noaalert

      - name: Run Unit Tests
        run: go test -v -coverprofile=coverage.txt -covermode=atomic --race ./...

      - name: Coverage Report
        run: go tool cover -func=coverage.txt

  build:
    name: Go Build
    runs-on: ubuntu-latest
    env:
      GOPATH: ${{ github.workspace }}/go
      GOBIN: ${{ github.workspace }}/go/bin
    defaults:
      run:
        working-directory: ${{ env.GOPATH }}/src/github.com/bbengfort/noaalert
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.x

      - name: Cache Speedup
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          path: ${{ env.GOPATH }}/src/github.com/bbengfort/noaalert

      - name: Build
        run: go build ./cmd/...